services:
  postgres:
    image: postgres:16
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    network_mode: host
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
